### ISSUE TITLE
【徒競走】スタートボタンの位置、徒競走エリアの fix

### ISSUE THREAD

**Issue by hiracky16** [e2d3/web#15]
- [x] 初期実行をやめる
- [x] 徒競走エリアの縦幅を全体的に縮める
- [x] ~スタートボタンと記録の表の位置を徒競走エリアの上に移動させる~

**Comment by hiracky16** [comment]
スタートボタンを押してからスタートするように修正済み。

**Comment by xiushu53** [comment]
* ボタン位置変更なし
* 表示領域のサイズ変更(13inchでワンビュー)
* サイズ指定は@yamazakiさん
* アイコンの書き出し@yamazaki  "@x2.png"
